### ISSUE TITLE
Change Passwordda ikkalasiham required bo'lishi kerak!

### ISSUE THREAD

**Issue by sherozbek1706** [market-n/market-server#45]

**Comment by sherozbek1706** [comment]
![image](https://github.com/market-n/market-server/assets/91471554/8d566dde-24ab-4502-a4a8-92dc671cfe0a)

**Comment by ayubxon0711** [comment]
ok nice bro

**Comment by ayubxon0711** [comment]
> ![image](https://private-user-images.githubusercontent.com/91471554/263618147-8d566dde-24ab-4502-a4a8-92dc671cfe0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTMyMjM0ODIsIm5iZiI6MTY5MzIyMzE4MiwicGF0aCI6Ii85MTQ3MTU1NC8yNjM2MTgxNDctOGQ1NjZkZGUtMjRhYi00NTAyLWE0YTgtOTJkYzY3MWNmZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwODI4VDExNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMWVhN2U3ZDMzMzliY2ZhOTI4OWM5NThlOWQ0YTkzM2IxMjVkMGMxMDI1NDJkMWM1YjNhMDdjNzQwNjlhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwM83KsDuFgrR11UwPWF3ilyx0gPz360i5DSkr1FDhk)

qilindi
