### ISSUE TITLE
Swagger'ga o'zgartirish kerak!

### ISSUE THREAD

**Issue by sherozbek1706** [market-n/market-server#49]
![image](https://github.com/market-n/market-server/assets/91471554/ceaf7c84-b4d8-459b-a947-9d6d06fb8425)

**Shu bo'limni hamma so'rovga bitta bitta yozgandan ko'ra tashqariga olib chiqisni ko'rib chiqish kerak!**

**Comment by ayubxon0711** [comment]
> ![image](https://private-user-images.githubusercontent.com/91471554/263629541-ceaf7c84-b4d8-459b-a947-9d6d06fb8425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTMyMjM3MTksIm5iZiI6MTY5MzIyMzQxOSwicGF0aCI6Ii85MTQ3MTU1NC8yNjM2Mjk1NDEtY2VhZjdjODQtYjRkOC00NTliLWE5NDctOWQ2ZDA2ZmI4NDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwODI4VDExNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYzc4OGIwZjYxYzFmMmNjMzcwNzIwNjg4MGFhNWU5MjBjM2I1NjliNGNhMzY1OTZhZjU4ZTkzNDMyZmMxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CtYORIoFMI7c3_VOB0Dc3LwsGDtBgzxx1gse3Js7mns)
> 
> **Shu bo'limni hamma so'rovga bitta bitta yozgandan ko'ra tashqariga olib chiqisni ko'rib chiqish kerak!**

ok
