### ISSUE TITLE
Uploadni yasash kerak !  Kim bajara oladi ?

### ISSUE THREAD

**Issue by sherozbek1706** [market-n/market-server#51]
![image](https://github.com/market-n/market-server/assets/91471554/c2643546-424c-42c8-8fc4-177182cd938a)

**Comment by ayubxon0711** [comment]
manda

**Comment by ayubxon0711** [comment]
manda

**Comment by sherozbek1706** [comment]
Malades

чт, 14 сент. 2023 г., 23:51 Ayubxon ***@***.***>:

**Comment by sherozbek1706** [comment]
Bo'lmabdi qilmabsakku uka
